on:
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: |
      echo "Ajith"
    steps:
      - name: Ajith step
        run: echo "GITHUB_TOKEN: $secrets.GITHUB_TOKEN"
      - uses: Ajithkumarparthasarathy/automate-release-action@master
        with:
          bump_version_scheme: minor
        
